stages:
  - linting
  - test_install
  - deploy

default:
  image: python:3.10
  before_script:
    - apt-get update && apt-get install -y git
    - pip install poetry

linting:
  stage: linting
  before_script:
    - pip install pre-commit
  script:
    - pre-commit run --all-files --show-diff-on-failure

install_all:
  image : python:$PYTHON_VERSIONS
  stage: test_install
  parallel :
    matrix :
      - PYTHON_VERSIONS : [ "3.10", "3.11", "3.12", "3.13" ]
  script:
    - apt-get update && apt-get install -y git
    - pip install poetry
    - poetry config virtualenvs.in-project true
    - poetry install
    - source .venv/bin/activate

publish_internal:
  stage: deploy
  when: manual
  only:
    - master
  script:
    - poetry config repositories.gitlab ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi
    - poetry build
    - poetry publish --repository gitlab -u gitlab-ci-token -p ${CI_JOB_TOKEN}
  environment:
    name: staging
    url: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi

push_to_external_pipy_test_registry:
  stage: deploy
  when: manual
  only:
    - master
  script:
    - poetry config repositories.test https://test.pypi.org/legacy/
    - poetry build
    - poetry publish --repository test -u __token__ -p ${CR_PYPI_TEST_API_TOKEN}

push_to_external_pipy_release_registry:
  stage: deploy
  when: manual
  only:
    - master
  script:
    - poetry build
    - poetry publish -u __token__ -p ${CR_PYPI_RELEASE_API_TOKEN}
