[project]
name = "commonroad-all"
version = "0.1.1"
description = "Meta-Package for installing all CommonRoad Tools"
authors = [
    { name = "Cyber-Physical Systems Group, Technical University of Munich", email = "commonroad@lists.lrz.de" },
]
license = "GPL-3.0-or-later"
readme = "README.md"
keywords = ["autonomous", "automated", "vehicles", "driving", "motion", "planning", "simulation", "map", "scenario"]
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Operating System :: POSIX :: Linux",
]
requires-python = ">=3.10, <3.12"

dependencies = [
    "commonroad-io (>=2024.2, <2025.0.0)",
    "commonroad-route-planner (>=2025.1.0, <2026.0.0)",
    "commonroad-scenario-factory (>=2.0.0, <3.0.0)",
    "commonroad-ots (>=2025.1, <2026.0.0)",
    "commonroad-sumo (>=2025.1, <2026.0.0)",
    "commonroad-labeling (>=2025.1.1, <2026.0.0)",
    "commonroad-crime (>=0.4.4, <0.5.0)",
    "commonroad-drivability-checker (>=2025.3.1, <2026.0.0)",
    "commonroad-clcs (>=2025.2.0, <2026.0.0)",
    "commonroad-global-planner (>=0.0.1, <0.1.0)",
    "commonroad-velocity-planner (>=1.0.0, <2.0.0)",
    "commonroad-reactive-planner (>=2025.1, <2026.0.0)",
    "commonroad-idm-planner (>=0.0.1, <1.0.0)",
    "commonroad-global-planner (>=0.0.1, <1.0.0)",
    "commonroad-raceline-planner (>=0.1.1, <0.2.0)",
    "commonroad-prediction (>=0.1.1, <0.2.0)",
#    "commonroad-openscenario-converter (>=0.1.1, <0.2.0)", # TODO should be fixed when scenario-designer is updated
    "commonroad-reach (>=2025.2.0, <2026.0.0)",
    "commonroad-dataset-converter (>2023.2, <=2025.1.0)",
#    "commonroad-scenario-designer (>=0.8.4, <0.9.0)",  # TODO update drivability checker
    # TODO fix all below packages
#    "commonroad-vehicle-models (>=3.0.2, <4.0.0)",
#    "commonroad-path-toolkit (>=0.0.1, <0.1.0)",
#    "commonroad-carla-interface (>=1.0.0, <2.0.0)",  # TODO python version must be updated
#    "commonroad-rl (>=2023.1.3, <2024.0.0)",  # TODO commonroad-route-planner version must be updated
#    "commonroad-geometric (>=0.1.2, <0.2.0)",  # TODO python version must be updated
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
